#!/bin/bash

folderpath="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
echo $folderpath > /dev/null
rsync -a --include='*model*.txt' --include='*/' --exclude='*' yoda:/nfs.yoda/gsigurds/caches/ $folderpath/../results/ > /dev/null\
&& echo '     >>>>    Sync successful.    <<<<     ' &


